### ISSUE TITLE
Icon on marked folder

### ISSUE THREAD

**Issue by serhiijun** [vquelque/vscode_mark_files#6]
Currently, I can't see a checkmark on the marked folder, is that possible to fix that?

**Comment by vquelque** [comment]
HI @serhiijun,
Unfortunately, as of today, the VS Code API does not provide any way to add a checkmark on the marked folder. We can only change the color of the folder name, and add a colored round mark. Both of these features are already implemented. 
In the future, if the VSCode API provides better customization options for the folders in the explorer, I'll definitely implement that 😀!
