### ISSUE TITLE
Importing and exporting via scope.txt does not work

### ISSUE THREAD

**Issue by Scorpiondeng** [vquelque/vscode_mark_files#7]
After executing reload, it will only display the loaded file and get stuck.

![image](https://github.com/vquelque/vscode_mark_files/assets/49943935/2fc70999-e85f-4b82-a6e0-aa716743dd99)

**Comment by vquelque** [comment]
@Scorpiondeng I'm not sure to understand what's not working? once you reload from the scope file, are the file correctly marked in the explorer?

**Comment by Scorpiondeng** [comment]
It has not been marked. I am running win11 system and I have tried it on several computers. After reload, all previous marks are cleared, and then there is no follow-up.

**Comment by vquelque** [comment]
@Scorpiondeng Are you sure that the paths in the scope file are correct? The paths should be relative to the location of the scope file itself. Could you try to manually mark some file, "Export marked files to a file" from the context menu, unmark some of the files, and then reload the marks by running the "Reload marked files from scope file". Normally, all the marks should re-appear.

**Comment by Scorpiondeng** [comment]
Yeah, I've also doubted this. So I tried Export, but nothing happened, no files were exported. I've also tried various different paths, all of which failed.

**Comment by vquelque** [comment]
Ok, weird. Could you check if there is any error message displayed in the VSCode output? In the "Mark Files" and "Extension host"   outputs?

**Comment by Scorpiondeng** [comment]
There is such a display when exporting, but there is no output when reloading. There is no output in "Extension host"
![image](https://github.com/vquelque/vscode_mark_files/assets/49943935/999dcc0c-2a32-40ea-9ea1-f012fc97d893)

**Comment by vquelque** [comment]
I guess it's probably a problem related to Windows, somehow. I'm only using Mac OS and linux machines, so it's harder for me to debug 😅 I'm gonna try to get access to a windows machine asap to try.

**Comment by Scorpiondeng** [comment]
Thank you for your kind help

**Comment by X1pherW0lf** [comment]
Has the issue been fixed? I’m still running into the same problem.

on v1.1.3

**Comment by Scorpiondeng** [comment]
It's been fixed and so far everything is fine.

**Comment by X1pherW0lf** [comment]
Got it. It’s working now. There was a format issue.
